import { Roboto } from 'next/font/google'
import { Providers } from './providers'
import "../styles/global.css";
import Navbar from '../components/common/Navbar'
import BottomNav from "@/components/common/BottomNav"
import { Container } from '@chakra-ui/react';

const roboto = Roboto({ subsets: ['latin'], weight: '100' })

export const metadata = {
  title: 'Todo Gamers Challenge',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
          <Container maxW='425px' p={0}>
            <Navbar />
              {children}
            <BottomNav />
          </Container>
        </Providers>
      </body>
    </html>
  )
}
